server:
  port: 8081
spring:
  application:
    name: financial
  main:
    allow-bean-definition-overriding: true
  boot:
    admin:
      client:
        url: http://192.168.0.100:7008
        instance:
          prefer-ip: true
  datasource:
    url: jdbc:mysql://47.105.39.255:13306/ml_financial?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
logging:
  level:
    com.bbs.financial: debug
    com.bbs.api: error
    com.baomidou: debug
  file:
    path: logs/financial
  config: classpath:logback-spring.xml
news:
  image:
    path: E:\ideawork\native-bbs-system\native-bbs-service\src\main\resources\nview\
    down:
      prefix: /image
  file:
    path: E:\ideawork\native-bbs-system\native-bbs-service\src\main\resources\nfile\
    down:
      prefix: /file
  video:
    path: E:\ideawork\native-bbs-system\native-bbs-service\src\main\resources\nvideo\
    down:
      prefix: /video
apache:
  zookeeper:
    # 服务器连接地址，集群模式则使用逗号分隔如：ip1:host,ip2:host
    connect-url: 192.168.0.100:2181
    # 会话超时时间：单位ms
    session-timeout: 10000
    # 连接超时时间：单位ms
    connection-timeout: 10000
    # ACL权限控制，验证策略
    scheme: auth
    # 验证内容id
    auth_id: admin:123456
  # 重试策略
  retry-policy:
    # 初始化间隔时间
    base-sleep-time: 1000
    # 最大重试次数
    max-retries: 5
    # 最大重试间隔时间
    max-sleep: 30000
auth:
  host: 192.168.0.100:8515
  api:
    verify:
      path: /verify
      token: Authorization
      timeout: 10000
    search:
      id: /server/
      list: /server/list
tianditu:
  host: http://api.tianditu.gov.cn
  tk: ab3e7b4366baee49f295a3e58185a557
  api:
    search: /geocoder
    timeout: 10000
dfs:
  host: 192.168.0.7:8082
  api:
    deleteList: /batch
    timeout: 10000
# Spring Admin 开启监控所有项
management:
  endpoints:
    web:
      exposure:
        include: "*"
dubbo:
  application:
    name: financial
    qos-enable: false
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://${apache.zookeeper.connect-url}