spring:
  application:
    name: dfs
  boot:
    admin:
      client:
        url: http://localhost:7003
        instance:
          prefer-ip: true
  redis:
    host: 192.168.100.6
    port: 6379
  # 以下配置会影响：日志上报功能
  rabbitmq:
    addresses: 127.0.0.1:5672
    port: 5672
    username: admin
    password: admin
    virtual-host: /test/host
    publisher-returns: true
    publisher-confirm-type: correlated
server:
  port: 8082
logging:
  level:
    com.bbs.file: debug
    com.baomidou: debug
    com:
      github:
        tobato:
          fastdfs: debug
  file:
    path: logs/dfs/
  config: classpath:logback-spring.xml
fdfs:
  so-timeout: 1500 # socket 连接时长
  connect-timeout: 600 # 连接 tracker 服务器超时时长
  # 这两个是你服务器的 IP 地址，注意 23000 端口也要打开，阿里云服务器记得配置安全组。tracker 要和 stroage 服务进行交流
  tracker-list: 192.168.100.6:22122
  web-server-url: 192.168.100.6:8888
  pool:
    jmx-enabled: false
  # 生成缩略图
  thumb-image:
    height: 500
    width: 500
management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
  endpoint:
    logfile:
      external-file: logs/dfs/