spring:
  application:
    name: dfs
  main:
    allow-bean-definition-overriding: true
  boot:
    admin:
      client:
        url: http://192.168.0.100:7008
        instance:
          prefer-ip: true
  redis:
    host: 192.168.0.100
    port: 6379
    password: shenbimaliang
  # 以下配置会影响：日志上报功能
  rabbitmq:
    addresses: 192.168.0.100
    port: 5672
    username: admin
    password: shenbimaliang
    virtual-host: bthost
    publisher-returns: true
    publisher-confirm-type: correlated
  servlet:
      multipart:
        max-file-size: 1024MB        # 设置单个文件最大大小
        max-request-size: 1024MB
server:
  port: 8082
logging:
  level:
    com.bbs.file: debug
    com.baomidou: debug
    com:
      github:
        tobato:
          fastdfs: debug
  file:
    path: logs/dfs/
  config: classpath:logback-spring.xml
#账号 auth/2Bq7LddkUxc4CqTv
minio:
  endpoint: http://192.168.0.100:9000 #Minio服务所在地址
  bucketName: maliang #存储桶名称
  accessKey: DJXY6R4T7AS8F3AJDLO3 #访问的key
  secretKey: FFXjJHNiAJ0V+bFMrsFmKbKLRjrLUZWip2jFHz1i #访问的秘钥
management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
  endpoint:
    logfile:
      external-file: logs/dfs/