server:
  port: 8424

spring:
  application:
    name: stream-manage
  main:
    allow-bean-definition-overriding: true
  datasource:
    dynamic:
      primary: stream
      strict: false
      datasource:
        stream:
          url: jdbc:mysql://47.105.39.255:13306/ml_stream_manage?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
        auth:
          url: jdbc:mysql://47.105.39.255:13306/ml_auth?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.0.100
    port: 6379
    password: shenbimaliang
  rabbitmq:
    username: admin
    password: shenbimaliang
    addresses: 192.168.0.100:5672
    virtual-host: bthost
    connection-timeout: 15000
    listener:
      simple:
        concurrency: 5 #并发
        max-concurrency: 10 #最大并发
        prefetch: 1 #每次发送一条消息
        acknowledge-mode: manual #手动回复ack

# 自定义文档访问的地址，http://localhost:8080/sss
springdoc:
  swagger-ui:
    path: /stream-manage-api
  # 需要扫描的包路径
  packagesToScan: com.bbs.stream
  # 匹配的url路径
  pathsToMatch: /*

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl

logging:
  level:
    com:
      baomidou: debug
      bbs:
        stream-manage: debug
        api: info
  file:
    path: logs/stream-manage/
  config: classpath:logback-spring.xml

jwt:
  #  token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9
  name: token
  token: 123456
  expireTime: 7

tokenName: Authorization
authServerIP: 192.168.100.6
authServerPort: 8080
auth:
  host: 192.168.0.100:8515
  api:
    verify:
      path: /verify
      token: authorization
      timeout: 10000
    search:
      id: /server/
      list: /server/list