server:
  port: 8084
  error:
    include-message: always
spring:
  application:
    name: auth
  main:
    allow-bean-definition-overriding: true
  boot:
    admin:
      client:
        url: http://172.31.62.123:32148
        instance:
          service-base-url: http://47.105.39.255:32149
          prefer-ip: true
          metadata:
            logfiles:
              info: http://47.105.39.255:32146/logfile/info
              error: http://47.105.39.255:32146/logfile/error
  datasource:
    url: jdbc:mysql://192.168.31.35:3306/auth?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.31.191
    port: 6551
    # password: 5mCw8N8h
    timeout: 10000
    redisson:
      config:
        singleServerConfig:
          idleConnectionTimeout: 10000
          connectTimeout: 10000
          timeout: 3000
          retryAttempts: 3
          retryInterval: 1500
          address: redis://192.168.31.191:6551
          # password: 5mCw8N8h
          clientName: null
          keepAlive: false
          tcpNoDelay: false
        threads: 16
        nettyThreads: 32
        transportMode: "NIO"
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
logging:
  level:
    com.bbs.auth: debug
    com.baomidou: debug
  file:
    path: logs/auth
  config: classpath:logback-spring.xml
jwt:
  #  token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9
  name: Authorization
  token: 123456
  expireTime: 7
management:
  endpoints:
    web:
      exposure:
        include: "*"
    logfile:
      enabled: true
      external-file: /home/auth/logs/auth
      info-file: /home/auth/logs/auth/info
      error-file: /home/auth/logs/auth/error
    health:
      show-details: always


dubbo:
  application:
    name: auth
    qos-enable: false
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://192.168.31.191:8848?namespace=3feadc28-5122-4134-97b0-011ed4169b8b
    timeout: 50000
    parameters:
      blockUntilConnectedWait: 50
  config-center:
    address: nacos://192.168.31.191:8848
  metadata-report:
    address: nacos://192.168.31.191:8848
code:
  alibaba:
    endpoint: dysmsapi.aliyuncs.com
    access:
      key: LTAI5t8Rqfdfm1Mdd1Lke4K5
      secret: LmxzctYpuvEfRGUBRPB71JVgKgpTKM
    sign: 济源商业平台
    template: SMS_465343610
  feigeyun:
    apikey: N120300ed85
    secret: 120300cf44753590d
    sign: 212925
    template: 190260
wx:
  oa:
    appId: wxbd377f32afa2d442
    appSecret: 9fe6c48d6689198f4d0022f3e809c3bb
    token: nKjjt1fBXVxyyLC4
  pay:
    merchantId: "1681624897"
    privateKeyPath: D:\project\jiyuan-chamber-of-commerce-end\auth\src\main\resources\wx\apiclient_key.pem
    merchantSerialNumber: 5721D46FCEB001585844D195A3CBF2CD37402052
    apiV3Key: jhdfhen274612BDGFSndcVBS6BD5r4ds
filter:
  bloom:
    phone:
      name: bloom:phone
      expected: 100000
      probability: 0.0001
      threshold: 0.75
user:
  register:
    inviteValidDay: 365
    try:
      day: 7
api:
  management:
    permission:
      code: fdlnfkergb62utku