spring:
  application:
    name: monitoring
  rabbitmq:
    username: admin
    password: shenbimaliang
    addresses: 192.168.0.100:5672
    virtual-host: bthost
    connection-timeout: 15000
    listener:
      simple:
        concurrency: 5 #并发
        max-concurrency: 10 #最大并发
        prefetch: 1 #每次发送一条消息
        acknowledge-mode: manual #手动回复ack
server:
  port: 7003
logging:
  level:
    com.bbs.monitoring: debug
  file:
    path: l ogs/monitor
  config: classpath:logback-spring.xml