server:
  port: 8080
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://192.168.100.8:3306/native_bbs?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    username: admin
    password: admin
    addresses: 192.168.100.6:5672
    virtual-host: /test/host
    connection-timeout: 15000
    listener:
      simple:
        concurrency: 5 #并发
        max-concurrency: 10 #最大并发
        prefetch: 1 #每次发送一条消息
        acknowledge-mode: manual #手动回复ack
  redis:
    host: 192.168.100.6
    port: 6379
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
      resolve-lazily: false
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
logging:
  level:
    com.bbs.content: debug
    com.baomidou: debug
  file:
    path: logs/
  config: classpath:logback-spring.xml
news:
  image:
    path: E:\ideawork\native-bbs-system\native-bbs-service\src\main\resources\nview\
    down:
      prefix: /image
  file:
    path: E:\ideawork\native-bbs-system\native-bbs-service\src\main\resources\nfile\
    down:
      prefix: /file
  video:
    path: E:\ideawork\native-bbs-system\native-bbs-service\src\main\resources\nvideo\
    down:
      prefix: /video
jwt:
  #  token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9
  name: token
  token: 123456
  expireTime: 7
apache:
  zookeeper:
    # 服务器连接地址，集群模式则使用逗号分隔如：ip1:host,ip2:host
    connect-url: 192.168.100.6:2181
    # 会话超时时间：单位ms
    session-timeout: 10000
    # 连接超时时间：单位ms
    connection-timeout: 10000
    # ACL权限控制，验证策略
    scheme: auth
    # 验证内容id
    auth_id: admin:123456
  # 重试策略
  retry-policy:
    # 初始化间隔时间
    base-sleep-time: 1000
    # 最大重试次数
    max-retries: 5
    # 最大重试间隔时间
    max-sleep: 30000
tokenName: Authorization
authServerIP: 192.168.100.6
authServerPort: 8080
