server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://152.136.163.92:3306/clinic?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: AvQ5rJPdFh8e
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
#      host: 152.136.163.92
#      port: 6379
    host: bj-crs-j1ozavqn.sql.tencentcdb.com
    port: 21800
    password: fsdef12vfsd
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
logging:
  level:
    com.clinic: debug
    com.baomidou: debug
  file:
    path: logs/
  config: classpath:logback-spring.xml

tokenName: token
authServerIP: localhost
authServerPort: 9999

prescription:
  template:
    path: E:\ideawork\clinic-system\clinic-service\src\main\resources\templates
  image:
    path: E:\ideawork\clinic-system\clinic-service\src\main\resources\preview
    down:
      prefix: /image
  file:
    path: E:\ideawork\clinic-system\clinic-service\src\main\resources\prescriptions
    down:
      prefix: /file
diagnosis:
  template:
    path: E:\ideawork\clinic-system\clinic-service\src\main\resources\diagnosis
setting:
  stock:
    expiry:
      alert:
       month: 3